### ISSUE TITLE
unexpected behaviour

### ISSUE THREAD

**Issue by kaat0** [zenodraft/action#19]
I used the action with the option `filenames: release.zip`, and it succeeded. But it had consequences I was not aware of:
- there were two uploads to zenodo:
      1. the file release.zip
      2. a snapshot of the repo
- a GitHub release
- a version tag on the repo

The GitHub action of zenodraft encompasses quite a lot of functionality. And I do get that there is a scenario where this is handy! But it does not fit in a workflow with other tasks. E.g., If I want to specify release notes with my GitHub release or need to upload the artifact to other services triggered by a tag push from the maintainer. See also https://github.com/zenodraft/action/issues/16.

Could you:
- [ ] please specify the functionality in the documentation/README
- [ ] provide toggles to turn off GitHub release and version tagging

I guess that the double upload to zenodo is unintended. My workaround is to use the CLI zenodraft since it seems that it can be used granularly.

**Comment by kaat0** [comment]
For documentation purposes; my workaround:

```YAML
- name: "install zenodraft"
  run: npm install -g zenodraft

- name: "download artifact"
  uses: actions/download-artifact@v3

- name: "uploading to zenodo sandbox"
  env:
    ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
  run: |
    COLLECTION=1048737
    NEW_DOI=$(zenodraft --sandbox deposition create in-existing-collection $COLLECTION)
    zenodraft --sandbox file add $NEW_DOI artifact/release.zip
    zenodraft --sandbox metadata update $NEW_DOI artifact/metadata.json
    zenodraft --sandbox deposition publish $NEW_DOI
```
