### ISSUE TITLE
Using the github <-> Zenodo integration mutually exclusive with zenodraft action?

### ISSUE THREAD

**Issue by alexlancaster** [zenodraft/action#22]
After getting duplicate uploads when enabling both the zenodraft action and the integration github <-> zenodo here: https://sandbox.zenodo.org/account/settings/github/  I finally realized that (I think) they are mutually exclusive, is that correct?

I am getting a separate upload from zenodraft, and it also doesn't seem to include the version taken from `git tag` as the integration does.  Has the integration superceded this action?  One thing that the integration doesn't do, which this action does, it up date the `CITATION.cff` file, which is the reason I tried using it, but it loses the ability to use the git tag.

**Comment by jspaaks** [comment]
Hi @alexlancaster, thanks for making the issue. Indeed the GitHub integration and `zenodraft` should be mutually exclusive. The GitHub integration predates `zenodraft` by a few years.

> it also doesn't seem to include the version taken from `git tag`

Correct, it tries to use metadata bundled with the repo files, e.g. from `version` in the file listed as `metadata`'s value.

PS which repo does this happen on? It's always useful for me to see how `zenodraft` is being used "in the wild", so to speak.

**Comment by alexlancaster** [comment]
> Hi @alexlancaster, thanks for making the issue. Indeed the GitHub integration and `zenodraft` should be mutually exclusive. The GitHub integration predates `zenodraft` by a few years.
> 
> > it also doesn't seem to include the version taken from `git tag`
> 
> Correct, it tries to use metadata bundled with the repo files, e.g. from `version` in the file listed as `metadata`'s value.

Is there a way to handle it like the integration does? I asked because I set the version by creating a tag with the version number during the release and that's the only place that I ever set the version number. The integration nicely passes this along to zenodo.

> PS which repo does this happen on? It's always useful for me to see how `zenodraft` is being used "in the wild", so to speak.
> 

Sure, it's in the pypop repo in a branch right now:

https://github.com/alexlancaster/pypop/tree/zenodo_upload
 
https://github.com/alexlancaster/pypop/blob/00fb19161d053fef30f26a28a744fca9674e1fce/.github/workflows/build_wheels.yml#L123

PS. It seems that as of a couple of days ago, sandbox.zenodo.org isn't working properly with this migration going on, so I haven't been able to test it for a few days. Have you had the same problem?

**Comment by jspaaks** [comment]
OK, so if I understand you correctly you want the tag that is entered in GitHub when you make the release to be the single source of truth for the version string. 

How about something like this using `jq` and `yq` (command line programs to manipulate JSON and YAML respectively):

```yaml
jobs:
  publish_zenodo:
    name: Publish to zenodo on production releases only
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published' && '!github.event.release.prerelease'
    steps:
       - name: Checkout the contents of your repository
         uses: actions/checkout@v4
       - name: Upsert the version in the metadata in .zenodo.json
         run: |
           cp .zenodo.json .zenodo.orig.json
           echo "{\"version\": \"$GITHUB_REF_NAME\"}" | cat .zenodo.orig.json - | jq -s add > .zenodo.json
           rm .zenodo.orig.json
       - name: Upsert the version in the metadata in CITATION.cff
         run: |
           yq -i ".version = \"$GITHUB_REF_NAME\"" CITATION.cff
       - name: Push changes back to repo files
         run: |
           git config --global user.name ci
           git config --global user.email "ci@users.noreply.github.com"
           git add .zenodo.json CITATION.cff
           git commit -m "Upserted version into CITATION.cff and into .zenodo.json"
           git push origin $GITHUB_REF_NAME
       - name: Create a draft snapshot of your repository contents as a new
               version in collection 1243488 on Zenodo Sandbox using metadata
               from repository file .zenodo.json
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
         uses: zenodraft/action@0.10.0
         with:
           collection: 1243488
           metadata: .zenodo.json
           publish: true
           sandbox: true
           compression: tar.gz
           upsert-doi: true
           upsert-location: doi
```

BTW I just tried using Zenodo Sandbox and indeed that seems to have changed in the last few days, probably something to do with the migration. I don't know if zenodraft will keep working once the migration is done, there could be API changes maybe. So anyway I tested the above on one of my collections on real Zenodo, that seems to work like it used to but I expect it will change once the Zenodo folks like what they are seeing with Sandbox.

O BTW I had to update your `.zenodo.json`, it had a trailing comma near the bottom which `jq` didn't like. Also, there was a version string in CITATION.cff that gets overridden with the value from the tag now. Just so you know.

PS my fork of the workflow with my changes is here for the time being https://github.com/jspaaks/pypop/blob/32fa216ef7bbbbfd17319ad80cbc50f4c43afbd4/.github/workflows/build_wheels.yml#L1

Hope this helps you! Best regards,
-Jurriaan
