### ISSUE TITLE
Avoid having to do your own checkout in user workflows

### ISSUE THREAD

**Issue by jspaaks** [zenodraft/action#5]
so instead of 

```yaml
        - name: checkout
          uses: actions/checkout@v2      
        - name: Create a draft deposition in a new collection
          env:
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}        
          uses: zenodraft/action@0.7.0
```

it would be better to have 
```yaml
        - name: Create a draft deposition in a new collection
          env:
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}        
          uses: zenodraft/action@0.7.0
```

**Comment by kaat0** [comment]
Hi

I just want to submit a new release inside an artifact with `filenames` from a previous job. the checkout does not seem necessary to me.

```
- uses: actions/download-artifact@v3

- name: "uploading to zenodo sandbox"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
  uses: zenodraft/action@0.10.0
  with:
    filenames: artifact/release.zip
```
